[VTS FIX] Wifi: iwlmvm: enable vendor-cmd for vts test
projectceladon/linux-intel-lts2022 pull request #14
Opened 2024-07-22 02:15 UTC by zhaoye1

for VtsHalWifiChipTargetTest
wifi_chip_->requestChipDebugInfo(&debug_info).isOk() will failed

Test:
After put on this patch,
VtsHalWifiChipTargetTest can pass

Tracked-On: OAM-OAM-122485
Change-Id: Ic345a75ef08ff07dd96164fe8d13011208b57a2a

2024-07-22 02:17 UTC, sysopenci commented
Improper Commit Message
Proper Tracked on value is not present in
    commit message,make sure Tracked-on: jira-ticket is present

2024-07-22 02:17 UTC, sysopenci commented
Improper Commit Message
Proper Tracked on value is not present in
    commit message,make sure Tracked-on: jira-ticket is present

2024-07-22 02:24 UTC, dyang23 approved these changes

2024-07-22 02:25 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-22 02:34 UTC, zhy1030 approved these changes

2024-07-22 02:39 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-22 02:40 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-22 02:55 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-22 02:55 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-22 03:55 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-22 06:35 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-22 06:56 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-22 07:09 UTC, JeevakaPrabu requested changes
please change the commit message. If you are ok, can you use this?

Wifi: iwlmvm: enable vendor-cmd for vts test

VtsHalWifiChipTargetTest is failing as the vendor
command requests are failing.

Vendor command file is compiled based on CONFIG_IWLMEI.
As CONFIG_IWLMEI is not enabled, vendor command is not
compiled at all.

Fix the issue by unconditionally compiling the vendor
command file.

Test:
VtsHalWifiChipTargetTest can pass

Tracked-On: OAM-122539
Change-Id: Ic345a75ef08ff07dd96164fe8d13011208b57a2a
Signed-off-by: Zhao Ye <zhao.ye@intel.com>

2024-07-22 07:43 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-22 12:33 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-23 00:11 UTC, zhaoye1 commented
> please change the commit message. If you are ok, can you use this?
> 
> Wifi: iwlmvm: enable vendor-cmd for vts test
> 
> VtsHalWifiChipTargetTest is failing as the vendor command requests are failing.
> 
> Vendor command file is compiled based on CONFIG_IWLMEI. As CONFIG_IWLMEI is not enabled, vendor command is not compiled at all.
> 
> Fix the issue by unconditionally compiling the vendor command file.
> 
> Test: VtsHalWifiChipTargetTest can pass
> 
> Tracked-On: OAM-122539 Change-Id: Ic345a75ef08ff07dd96164fe8d13011208b57a2a Signed-off-by: Zhao Ye [zhao.ye@intel.com](mailto:zhao.ye@intel.com)

updated

2024-07-23 00:19 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-23 01:50 UTC, dyang23 approved these changes

2024-07-23 03:11 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-23 03:36 UTC, JeevakaPrabu approved these changes

2024-07-23 08:01 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-23 08:02 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-23 08:16 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-23 13:36 UTC, merged

2024-07-23 13:55 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon-merge/684