Add PCI Subsystem ID to diff IVSheme device
projectceladon/linux-intel-lts2022 pull request #23
Opened 2024-08-12 06:47 UTC by xyzhao2018

Test Done:

adb reboot twice successfully.
power on, power off work normally.
adb, BT, Wi-Fi audio work normally.

Tracked-On: OAM-120375

2024-08-12 06:48 UTC, sysopenci commented
Program name for this pr is not compatable with other dependent prs, for more details please check tracked_on

2024-08-12 06:50 UTC, sysopenci commented
Program name for this pr is not compatable with other dependent prs, for more details please check tracked_on

2024-08-18 14:17 UTC, dyang23 approved these changes

2024-08-19 08:14 UTC, JeevakaPrabu requested changes
IVSheme => IVShmem

2024-08-19 08:15 UTC, JeevakaPrabu requested changes
Please define the sub device ids to a meaningful macro

2024-08-20 00:29 UTC, dyang23 approved these changes

2024-08-20 06:00 UTC, kaushlen approved these changes

2024-08-20 06:10 UTC, JeevakaPrabu approved these changes

2024-08-20 10:08 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-20 14:32 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-20 21:16 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-21 02:39 UTC, merged

2024-08-21 03:07 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon_umr0_master-merge/19