drm/virtio: Expose allow_p2p capability to user space
projectceladon/linux-intel-lts2022 pull request #40
Opened 2024-09-05 10:03 UTC by phreer

2024-09-05 10:04 UTC, sysopenci commented
Improper Commit Message
Tracked on not found in commit message,
    make sure Tracked-On: Jira-ticket  is present.

2024-09-09 07:20 UTC, sysopenci commented
Program name for this pr is not compatable with other dependent prs, for more details please check tracked_on

2024-10-18 02:19 UTC, feijiang1 approved these changes
LGTM

2024-10-23 08:46 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-10-23 08:48 UTC, xyzhao2018 requested changes
Please add test done part.

2024-10-23 08:56 UTC, xyzhao2018 approved these changes

2024-10-23 08:57 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-10-23 10:09 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-10-23 11:13 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-10-23 19:21 UTC, merged

2024-10-23 19:36 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon_umr0_master-merge/208